### ISSUE TITLE
Viewer options are broken in development build

### ISSUE THREAD

**Issue by jsub1** [glue-viz/glue#2019]
Drop-downs for the 3D scatter plot viewer and WWT viewer do not populate with the fields of the data set, and the only option that works for these viewer is changing the marker color via the color picker.

Based on local testing, it looks like this issue was introduced in pull request #1998.

**Comment by astrofrog** [comment]
I just fixed this yesterday - can you try updating?

**Comment by jsub1** [comment]
I still have this issue with the latest commit (cf2fc48).

**Comment by astrofrog** [comment]
@jsub1 - ah sorry you'll need the latest dev version of glue-wwt

**Comment by jsub1** [comment]
@astrofrog That fixed most of it. The marker size and color were still not hooked up correctly, so I just submitted a PR fixing that https://github.com/glue-viz/glue-wwt/pull/58
