### ISSUE TITLE
Selecting entries in a scatterplotted catalog fails sometimes

### ISSUE THREAD

**Issue by keflavich** [glue-viz/glue#702]
I have a complex link setup where I have a cube, a catalog, and a dendrogram all connected.

If I scatterplot the catalog's '_idx' column, which is linked to the dendrogram's 'index', the appropriate pixels are highlighted in the cube:

![image](https://cloud.githubusercontent.com/assets/143715/8634384/ef702c8e-27b3-11e5-8193-ce30621940f5.png)

This persists if I change the plotted axis:

![image](https://cloud.githubusercontent.com/assets/143715/8634382/dd661c88-27b3-11e5-8ce2-74e9701db856.png)

But as soon as I select anything in the new scatterplot, all the highlights disappear in the cube:

![image](https://cloud.githubusercontent.com/assets/143715/8634387/024d0318-27b4-11e5-8f53-f54569387b44.png)

If I add a new scatterplot, I can create highlights again, but *only* if I select on '_idx'.  If I use any other selection (circle, for example) that involves another axis, the highlights are gone.  It is as if the catalog's rows are not linked to one another.

**Comment by astrofrog** [comment]
@keflavich - when you do this, are there any errors in the error console? (or in the terminal if you are launching glue from the command-line)?

**Comment by keflavich** [comment]
@astrofrog - no errors, just these warnings:
```
WARNING:glue.config:could not get default tools for GlueVTKViewer
/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/text.py:52: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if rotation in ('horizontal', None):
/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/text.py:54: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif rotation == 'vertical':
```

I'm launching from a script:
https://github.com/adamginsburg/APEX_CMZ_H2CO/blob/master/analysis/dendro_glue.py

**Comment by astrofrog** [comment]
@keflavich - could you provide the data files, or alternatively send me a .glu session file that includes the data? (basically just save session and select 'including data' from the drop down menu in the save session window)

**Comment by astrofrog** [comment]
Ah, just realized these are the same as the files you sent by email. Will investigate.

**Comment by keflavich** [comment]
Sorry about the late note, but this patch:
https://github.com/keflavich/glue/commit/16064ee8f9c739eb04b856c62deb54a05c49890b
is required for my script to work

**Comment by astrofrog** [comment]
@keflavich - so to be clear, your patch fixes this issue? Or for glue to work at all?

**Comment by keflavich** [comment]
the patch is required for the script to work at all; it should crash partway through loading without the change.  It doesn't fix this issue.

**Comment by astrofrog** [comment]
Ok I will try and look into it today. I'm currently teaching at a summer school, so this week is pretty busy, but I'll make time for it today or tomorrow.

**Comment by ChrisBeaumont** [comment]
This think this isn't a bug, though it may be a clue for how to be more intuitive:

In plot 1 you selected a 1D swath along the _idx axis. This creates a subset whose logic is a boolean condition on idx. Glue knows how to select pixels based on this criteria, since dendrograms have an idx value at every pixel.

In plot 2 you selected a swath of a new variable, creating a subset whose logic is a boolean condition on that variable. That quantity is *not* defined at every pixel (at least in the way dendrograms are currently represented), so Glue doesn't know how to draw the subset (if you click on the image window, I expect the subset plot layer icon to turn into an X with a hover error message to that effect).

Conceptually we might say that the "r321303" is defined at every pixel, using the dendrogram structure index as a lookup. Glue however doesn't make this assumption by default IIRC.

Out of curiosity, do the pixels come back if you expand the subset in the upper left, right click on the dendrogram-specific subset, and click "transform subset to Pixel Mask"? That redefines the subset from a boolean condition on "r321303" to a boolean condition on dendrogram structure number. 

I'm open to suggestions for alternative behavior in this situation.

**Comment by keflavich** [comment]
"Transform subset to pixel mask" doesn't do anything as far as I can tell.

I see your point, but I still find this fairly unintuitive, perhaps because I'm not thinking about it the right way.  I expected the swath in `r321303` to select the catalog points, which are linked to the cube through `_idx`.  I think the issue is that I want `_idx` to be "special" in some way, e.g. to be one same/shared attribute between all of my data sets, which is different from being linked.

However, whether or not this behavior is intuitive, I really need the behavior I expect: I want to select on parameters in the catalog space and have the corresponding structures in the dendrogram get highlighted.  Is that possible?  It's fine if it requires additional setup, but I have no idea what that would be at this point.

**Comment by keflavich** [comment]
p.s. thanks for the X-icon + hover, I'd never appreciated that contained useful information before.

And second p.s. (this may belong on the glue-viz group): How do you recommend accessing/manipulating datasets in glue from within the ipython sessions in glue?  None of the variables I declare in the startup script are preserved in the glue session; is it possible to allow that (perhaps by passing `locals()` to `app.start()`?)

**Comment by ChrisBeaumont** [comment]
Sorry I spoke to soon here -- the 'join_on_key' function you use *should* permit the selection semantics that you expect. My guess is that in all the dataset merging some link got messed up, I'm looking into it

**Comment by ChrisBeaumont** [comment]
> How do you recommend accessing/manipulating datasets in glue from within the ipython sessions in glue

Anything you put in your config.py file will be pulled into the scope of the in-glue ipython session. It would be easy to add a session_context kwarg to GlueApplication, that forwards additional data into this (you would simply pass this through as additional keywords to glue_terminal inside GlueApplication._create_terminal. Care to open a PR?

**Comment by ChrisBeaumont** [comment]
Also, `dc` and `data_collection` hold the actual datasets in glue, which can also be aliased by dragging them into the terminal window

**Comment by ChrisBeaumont** [comment]
Ok, I think I figured it out:

![image](https://cloud.githubusercontent.com/assets/796752/8730704/4b1f7d2c-2ba7-11e5-9d68-68481a9b7edc.png)

See modified gist: https://gist.github.com/ChrisBeaumont/d809ee9d24735925c273

The main change I made was, instead of joining the catalog and Dendrogram on the _idx key, I merged the two datasets into a single dataset (this is what the glue UI will suggest you do when you interactively load 2 datasets with the same shape). 

Honestly I don't yet fully understand why your approach doesn't work, but my general advice is to always merge datasets with the same shape into one Data object, unless you have good reason not to. (I do see you have a commented-out version of this command, perhaps you *do* have a good reason not to?)

**Comment by keflavich** [comment]
It seems to come down to an order-of-arguments that I did not understand:
```
# does not work dc.merge(catalog, dendro)
dc.merge(dendro, catalog) # does work
```
and the does/not work happens because the `_idx` parameter gets consumed somehow by the merge operation.  I'm afraid I do not understand 'merging' at all.  

As you show, this gets me to the point that selecting dendrogram objects highlights pixels in the dendrogram cube.  However, it still does not highlight them in the other cube.  I think I need to merge my two cubes now... I'll try that.

**Comment by keflavich** [comment]
Followup: no, merging the cubes seems to only have effectively deleted the dendrocube structure (merging it into an attribute of h2cocube) without doing anything else.  I guess I'll need to find a way to re-link the dendrocube to the dendrogram after merging the cube and dendrocube.

Followup #2 b/c my internet is not so good and this was written offline: I've solved it now.  The key was doing a `join_on_structure` after merging.  I think my problems came from order-of-operations issues, especially because some operations seem to delete id's from datasets.

**Comment by astrofrog** [comment]
Maybe we should re-open this though since we should make this easier?

**Comment by ChrisBeaumont** [comment]
> I'm afraid I do not understand 'merging' at all.

@keflavich the current documentation on merging vs linking is at http://www.glueviz.org/en/stable/gui_guide/merging.html -- comments on how that explanation could be improved would be helpful (we should also add discussion of join_by_key)

The tl;dr is that you should merge datasets when each element measures different properties of the same "thing" (which also requires that the two datasets have the same shape).  

> an order-of-arguments that I did not understand

yeah that is surprising, and I think it's a bug. The dendro dataset has some extra hidden metadata that it gained during load_dendro (because load_dendro calls a `join_by_key`), and that metadata isn't getting merged. It probably should be possible to do this, such that the order of arguments in merge isn't important.

> I think I need to merge my two cubes now

That wouldn't work mainly because the two cubes are not pixel-aligned, so they don't have the same shape and don't measure the same region at each pixel.

Thinking through how all of this should work a bit more for a dendrogram (D), it's corresponding image (I1), and a second non-pixel-aligned image (I2):

Selections should propagate between I1 and I2 via normal WCS links. Selections propagate between I1 and D via the join_on_key.  I don't think that this is transitive though -- you couldn't propagate between D and I2. To do that, conceptually you would want to transform I2 pixel coordinates into I1 pixel coordinates, and then *interpolate* the index_map and apply the same logic as in join_on_key. That interpolation step is what's missing ATM.

**Comment by keflavich** [comment]
@ChrisBeaumont thanks.  One clarification, though: the two cubes *are* pixel-aligned.  So in this case, interpolation was not needed.

The main part of this process I found counterintuitive and hard to debug was when dataset attributes disappeared, which happened (I think) on both `merge` and `join_on_key` operations.  It would be helpful to see these still listed in the Glue linking dialogue, perhaps as  `(merged with [x])`

**Comment by ChrisBeaumont** [comment]
> the two cubes are pixel-aligned

Sorry, maybe I was looking at the wrong files (I was comparing 'APEX_13CO_2014_merge.fits' and 'APEX_H2CO_303_202_bl.fits' which have 500 and 300 velocity channels, respectively)

> when dataset attributes disappeared

Yeah this is confusing, I agree. When merging, all but the first dataset's pixel and world components are discarded, since they are redundant. That's annoying especially when the discarded components have a more informative name than the retained components (ie "Galactic Longitude" instead of "World 2"). 

This also comes up when defining simple links -- one component is dropped. I *think* the only problem with keeping redundant links around is that you start to see lots of repeated component names in any dialog to select components. But I like the idea of adding a `(merged with blah)` qualifier to the name, that might be a better way to keep things straight. 

So two concrete ideas from this thread so far:

 * Copy over join_by_key metadata when merging, so datasets can be merged in any order
 * Instead of dropping redundant components, keep them but relabel them to indicate they are redundant

And one unresolved problem:

 * How should selections propagate from A<->C when A<->B by a key join and B<->C is a spatial link. 

Maybe we should have some kind of toggle to say that, as a fallback, any dataset can spatially interpolate a subset as evaluated on another spatially-linked dataset, if it can't apply the subset's criteria on itself directly. There are situations when that's ambiguous, but maybe that's ok
